layout_spectrum: 0.2598566
color:
  saturation: 1
  brandStrength: 0.482747
  lightness: 0
  rhythmicContrast: 1
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
typography_spectrum: 0.6344086
name: Focus Designs
